-- THIS FILE IS GENERATED. Edit seeds_generators/countriesgenerator.py instead of this file.
insert into public.countries (
  iso2,
  name,
  capital,
  continent,
  primary_language,
  primary_language_code,
  primary_currency,
  primary_currency_code,
  flag_full_patch,
  background_hex
) values
  ('AD', 'Andorra', 'Andorra la Vella', 'Europe', 'Catalan', 'CAT', 'Euro', 'EUR', 'flags/AD.png', '#CC855BA0'),
  ('AE', 'United Arab Emirates', 'Abu Dhabi', 'Asia', 'Arabic', 'ARA', 'United Arab Emirates dirham', 'AED', 'flags/AE.png', '#CCAAAAAA'),
  ('AF', 'Afghanistan', 'Kabul', 'Asia', 'Dari', 'PRS', 'Afghan afghani', 'AFN', 'flags/AF.png', '#CC808080'),
  ('AG', 'Antigua and Barbuda', 'Saint John''s', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/AG.png', '#CC3E7269'),
  ('AI', 'Anguilla', 'The Valley', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/AI.png', '#CC566C9D'),
  ('AL', 'Albania', 'Tirana', 'Europe', 'Albanian', 'SQI', 'Albanian lek', 'ALL', 'flags/AL.png', '#CC96816F'),
  ('AM', 'Armenia', 'Yerevan', 'Asia', 'Armenian', 'HYE', 'Armenian dram', 'AMD', 'flags/AM.png', '#CC90590A'),
  ('AO', 'Angola', 'Luanda', 'Africa', 'Portuguese', 'POR', 'Angolan kwanza', 'AOA', 'flags/AO.png', '#CC735C4A'),
  ('AR', 'Argentina', 'Buenos Aires', 'South America', 'Guaraní', 'GRN', 'Argentine peso', 'ARS', 'flags/AR.png', '#CC936B07'),
  ('AS', 'American Samoa', 'Pago Pago', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'flags/AS.png', '#CC9F8D5B'),
  ('AT', 'Austria', 'Vienna', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'flags/AT.png', '#CC8E0C21'),
  ('AU', 'Australia', 'Canberra', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/AU.png', '#CC556B9B'),
  ('AW', 'Aruba', 'Oranjestad', 'North America', 'Dutch', 'NLD', 'Aruban florin', 'AWG', 'flags/AW.png', '#CCB06E89'),
  ('AX', 'Åland Islands', 'Mariehamn', 'Europe', 'Swedish', 'SWE', 'Euro', 'EUR', 'flags/AX.png', '#CC808264'),
  ('AZ', 'Azerbaijan', 'Baku', 'Europe', 'Azerbaijani', 'AZE', 'Azerbaijani manat', 'AZN', 'flags/AZ.png', '#CC777FA0'),
  ('BA', 'Bosnia and Herzegovina', 'Sarajevo', 'Europe', 'Bosnian', 'BOS', 'Bosnia and Herzegovina convertible mark', 'BAM', 'flags/BA.png', '#CC7FC27C'),
  ('BB', 'Barbados', 'Bridgetown', 'North America', 'English', 'ENG', 'Barbadian dollar', 'BBD', 'flags/BB.png', '#CC555B60'),
  ('BD', 'Bangladesh', 'Dhaka', 'Asia', 'Bengali', 'BEN', 'Bangladeshi taka', 'BDT', 'flags/BD.png', '#CC744B47'),
  ('BE', 'Belgium', 'Brussels', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'flags/BE.png', '#CC988002'),
  ('BF', 'Burkina Faso', 'Ouagadougou', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/BF.png', '#CC987C02'),
  ('BG', 'Bulgaria', 'Sofia', 'Europe', 'Bulgarian', 'BUL', 'Bulgarian lev', 'BGN', 'flags/BG.png', '#CC432278'),
  ('BH', 'Bahrain', 'Manama', 'Asia', 'Arabic', 'ARA', 'Bahraini dinar', 'BHD', 'flags/BH.png', '#CC881A12'),
  ('BI', 'Burundi', 'Gitega', 'Africa', 'French', 'FRA', 'Burundian franc', 'BIF', 'flags/BI.png', '#CC8E0C21'),
  ('BJ', 'Benin', 'Porto-Novo', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/BJ.png', '#CC987C02'),
  ('BL', 'Saint Barthélemy', 'Gustavia', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'flags/BL.png', '#CCA1775A'),
  ('BM', 'Bermuda', 'Hamilton', 'North America', 'English', 'ENG', 'Bermudian dollar', 'BMD', 'flags/BM.png', '#CCAA9f52'),
  ('BN', 'Brunei', 'Bandar Seri Begawan', 'Asia', 'Malay', 'MSA', 'Brunei dollar', 'BND', 'flags/BN.png', '#CC757575'),
  ('BO', 'Bolivia', 'Sucre', 'South America', 'Aymara', 'AYM', 'Bolivian boliviano', 'BOB', 'flags/BO.png', '#CCA9589D'),
  ('BQ', 'Caribbean Netherlands', 'Kralendijk', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/BQ.png', '#CC9CAB7B'),
  ('BR', 'Brazil', 'Brasília', 'South America', 'Portuguese', 'POR', 'Brazilian real', 'BRL', 'flags/BR.png', '#CCA25994'),
  ('BS', 'Bahamas', 'Nassau', 'North America', 'English', 'ENG', 'Bahamian dollar', 'BSD', 'flags/BS.png', '#CC778B92'),
  ('BT', 'Bhutan', 'Thimphu', 'Asia', 'Dzongkha', 'DZO', 'Bhutanese ngultrum', 'BTN', 'flags/BT.png', '#CCCB95C8'),
  ('BW', 'Botswana', 'Gaborone', 'Africa', 'English', 'ENG', 'Botswana pula', 'BWP', 'flags/BW.png', '#CC255575'),
  ('BY', 'Belarus', 'Minsk', 'Europe', 'Belarusian', 'BEL', 'Belarusian ruble', 'BYN', 'flags/BY.png', '#CC773F33'),
  ('BZ', 'Belize', 'Belmopan', 'North America', 'Belizean Creole', 'BJZ', 'Belize dollar', 'BZD', 'flags/BZ.png', '#CC6AA257'),
  ('CA', 'Canada', 'Ottawa', 'North America', 'English', 'ENG', 'Canadian dollar', 'CAD', 'flags/CA.png', '#CC990000'),
  ('CC', 'Cocos (Keeling) Islands', 'West Island', 'Asia', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/CC.png', '#CCAA539F'),
  ('CD', 'DR Congo', 'Kinshasa', 'Africa', 'French', 'FRA', 'Congolese franc', 'CDF', 'flags/CD.png', '#CC569DAE'),
  ('CF', 'Central African Republic', 'Bangui', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'flags/CF.png', '#CC4E6099'),
  ('CG', 'Republic of the Congo', 'Brazzaville', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'flags/CG.png', '#CC967E04'),
  ('CH', 'Switzerland', 'Bern', 'Europe', 'French', 'FRA', 'Swiss franc', 'CHF', 'flags/CH.png', '#CC4D4D4D'),
  ('CI', 'Ivory Coast', 'Yamoussoukro', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/CI.png', '#CCBE959E'),
  ('CK', 'Cook Islands', 'Avarua', 'Oceania', 'English', 'ENG', 'Cook Islands dollar', 'CKD', 'flags/CK.png', '#CC5A6F9E'),
  ('CL', 'Chile', 'Santiago', 'South America', 'Spanish', 'SPA', 'Chilean peso', 'CLP', 'flags/CL.png', '#CC185D82'),
  ('CM', 'Cameroon', 'Yaoundé', 'Africa', 'English', 'ENG', 'Central African CFA franc', 'XAF', 'flags/CM.png', '#CC987C02'),
  ('CN', 'China', 'Beijing', 'Asia', 'Chinese', 'ZHO', 'Chinese yuan', 'CNY', 'flags/CN.png', '#CC8F0298'),
  ('CO', 'Colombia', 'Bogotá', 'South America', 'Spanish', 'SPA', 'Colombian peso', 'COP', 'flags/CO.png', '#CC482377'),
  ('CR', 'Costa Rica', 'San José', 'North America', 'Spanish', 'SPA', 'Costa Rican colón', 'CRC', 'flags/CR.png', '#CC6B96A7'),
  ('CU', 'Cuba', 'Havana', 'North America', 'Spanish', 'SPA', 'Cuban convertible peso', 'CUC', 'flags/CU.png', '#CC1B5A7F'),
  ('CV', 'Cape Verde', 'Praia', 'Africa', 'Portuguese', 'POR', 'Cape Verdean escudo', 'CVE', 'flags/CV.png', '#CC727E59'),
  ('CW', 'Curaçao', 'Willemstad', 'North America', 'English', 'ENG', 'Netherlands Antillean guilder', 'ANG', 'flags/CW.png', '#CC4F6CA7'),
  ('CX', 'Christmas Island', 'Flying Fish Cove', 'Asia', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/CX.png', '#CC7586AE'),
  ('CY', 'Cyprus', 'Nicosia', 'Europe', 'Greek', 'ELL', 'Euro', 'EUR', 'flags/CY.png', '#CC798361'),
  ('CZ', 'Czechia', 'Prague', 'Europe', 'Czech', 'CES', 'Czech koruna', 'CZK', 'flags/CZ.png', '#CC587DA4'),
  ('DE', 'Germany', 'Berlin', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'flags/DE.png', '#CC990030'),
  ('DJ', 'Djibouti', 'Djibouti', 'Africa', 'Arabic', 'ARA', 'Djiboutian franc', 'DJF', 'flags/DJ.png', '#CC8C0E11'),
  ('DK', 'Denmark', 'Copenhagen', 'Europe', 'Danish', 'DAN', 'Danish krone', 'DKK', 'flags/DK.png', '#CC8E0C21'),
  ('DM', 'Dominica', 'Roseau', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/DM.png', '#CC55B054'),
  ('DO', 'Dominican Republic', 'Santo Domingo', 'North America', 'Spanish', 'SPA', 'Dominican peso', 'DOP', 'flags/DO.png', '#CCA45863'),
  ('DZ', 'Algeria', 'Algiers', 'Africa', 'Arabic', 'ARA', 'Algerian dinar', 'DZD', 'flags/DZ.png', '#CC381783'),
  ('EC', 'Ecuador', 'Quito', 'South America', 'Spanish', 'SPA', 'United States dollar', 'USD', 'flags/EC.png', '#CC5DADA0'),
  ('EE', 'Estonia', 'Tallinn', 'Europe', 'Estonian', 'EST', 'Euro', 'EUR', 'flags/EE.png', '#CC4D4D4D'),
  ('EG', 'Egypt', 'Cairo', 'Africa', 'Arabic', 'ARA', 'Egyptian pound', 'EGP', 'flags/EG.png', '#CC8E0C1B'),
  ('EH', 'Western Sahara', 'El Aaiún', 'Africa', 'Berber', 'BER', 'Algerian dinar', 'DZD', 'flags/EH.png', '#CCABABAB'),
  ('ER', 'Eritrea', 'Asmara', 'Africa', 'Arabic', 'ARA', 'Eritrean nakfa', 'ERN', 'flags/ER.png', '#CC7E599A'),
  ('ES', 'Spain', 'Madrid', 'Europe', 'Spanish', 'SPA', 'Euro', 'EUR', 'flags/ES.png', '#CC52938F'),
  ('ET', 'Ethiopia', 'Addis Ababa', 'Africa', 'Amharic', 'AMH', 'Ethiopian birr', 'ETB', 'flags/ET.png', '#CC989D4D'),
  ('FI', 'Finland', 'Helsinki', 'Europe', 'Finnish', 'FIN', 'Euro', 'EUR', 'flags/FI.png', '#CC2F496B'),
  ('FJ', 'Fiji', 'Suva', 'Oceania', 'English', 'ENG', 'Fijian dollar', 'FJD', 'flags/FJ.png', '#CC57A578'),
  ('FK', 'Falkland Islands', 'Stanley', 'South America', 'English', 'ENG', 'Falkland Islands pound', 'FKP', 'flags/FK.png', '#CC577097'),
  ('FM', 'Micronesia', 'Palikir', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'flags/FM.png', '#CC1F557B'),
  ('FO', 'Faroe Islands', 'Tórshavn', 'Europe', 'Danish', 'DAN', 'Danish krone', 'DKK', 'flags/FO.png', '#CC8E0C16'),
  ('FR', 'France', 'Paris', 'Europe', 'French', 'FRA', 'Euro', 'EUR', 'flags/FR.png', '#CC566F8D'),
  ('GA', 'Gabon', 'Libreville', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'flags/GA.png', '#CC987C02'),
  ('GB', 'United Kingdom', 'London', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'flags/GB.png', '#CC41598F'),
  ('GD', 'Grenada', 'St. George''s', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/GD.png', '#CC4A9448'),
  ('GE', 'Georgia', 'Tbilisi', 'Asia', 'Georgian', 'KAT', 'lari', 'GEL', 'flags/GE.png', '#CC990000'),
  ('GF', 'French Guiana', 'Cayenne', 'South America', 'French', 'FRA', 'Euro', 'EUR', 'flags/GF.png', '#CC988502'),
  ('GG', 'Guernsey', 'St. Peter Port', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'flags/GG.png', '#CC968404'),
  ('GH', 'Ghana', 'Accra', 'Africa', 'English', 'ENG', 'Ghanaian cedi', 'GHS', 'flags/GH.png', '#CC987C02'),
  ('GI', 'Gibraltar', 'Gibraltar', 'Europe', 'English', 'ENG', 'Gibraltar pound', 'GIP', 'flags/GI.png', '#CC8A7372'),
  ('GL', 'Greenland', 'Nuuk', 'North America', 'Greenlandic', 'KAL', 'krone', 'DKK', 'flags/GL.png', '#CC8E0C21'),
  ('GM', 'Gambia', 'Banjul', 'Africa', 'English', 'ENG', 'dalasi', 'GMD', 'flags/GM.png', '#CC8E0C1B'),
  ('GN', 'Guinea', 'Conakry', 'Africa', 'French', 'FRA', 'Guinean franc', 'GNF', 'flags/GN.png', '#CC987C02'),
  ('GP', 'Guadeloupe', 'Basse-Terre', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'flags/GP.png', '#CC7D8048'),
  ('GQ', 'Equatorial Guinea', 'Malabo', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'flags/GQ.png', '#CC4B5791'),
  ('GR', 'Greece', 'Athens', 'Europe', 'Greek', 'ELL', 'Euro', 'EUR', 'flags/GR.png', '#CC0B4D8F'),
  ('GT', 'Guatemala', 'Guatemala City', 'North America', 'Spanish', 'SPA', 'Guatemalan quetzal', 'GTQ', 'flags/GT.png', '#CC76965D'),
  ('GU', 'Guam', 'Hagåtña', 'Oceania', 'Chamorro', 'CHA', 'United States dollar', 'USD', 'flags/GU.png', '#CC56AF9B'),
  ('GW', 'Guinea-Bissau', 'Bissau', 'Africa', 'Portuguese', 'POR', 'West African CFA franc', 'XOF', 'flags/GW.png', '#CC987C02'),
  ('GY', 'Guyana', 'Georgetown', 'South America', 'English', 'ENG', 'Guyanese dollar', 'GYD', 'flags/GY.png', '#CC4AA27C'),
  ('HK', 'Hong Kong', 'City of Victoria', 'Asia', 'English', 'ENG', 'Hong Kong dollar', 'HKD', 'flags/HK.png', '#CC8F0B11'),
  ('HN', 'Honduras', 'Tegucigalpa', 'North America', 'Spanish', 'SPA', 'Honduran lempira', 'HNL', 'flags/HN.png', '#CC0F758B'),
  ('HR', 'Croatia', 'Zagreb', 'Europe', 'Croatian', 'HRV', 'Euro', 'EUR', 'flags/HR.png', '#CC5B5FAF'),
  ('HT', 'Haiti', 'Port-au-Prince', 'North America', 'French', 'FRA', 'Haitian gourde', 'HTG', 'flags/HT.png', '#CC66649E'),
  ('HU', 'Hungary', 'Budapest', 'Europe', 'Hungarian', 'HUN', 'Hungarian forint', 'HUF', 'flags/HU.png', '#CC477050'),
  ('ID', 'Indonesia', 'Jakarta', 'Asia', 'Indonesian', 'IND', 'Indonesian rupiah', 'IDR', 'flags/ID.png', '#CC990000'),
  ('IE', 'Ireland', 'Dublin', 'Europe', 'English', 'ENG', 'Euro', 'EUR', 'flags/IE.png', '#CC63BC96'),
  ('IL', 'Israel', 'Jerusalem', 'Asia', 'Arabic', 'ARA', 'Israeli new shekel', 'ILS', 'flags/IL.png', '#CC0D348D'),
  ('IM', 'Isle of Man', 'Douglas', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'flags/IM.png', '#CC8F885F'),
  ('IN', 'India', 'New Delhi', 'Asia', 'English', 'ENG', 'Indian rupee', 'INR', 'flags/IN.png', '#CC5D5AB5'),
  ('IO', 'British Indian Ocean Territory', 'Diego Garcia', 'Asia', 'English', 'ENG', 'United States dollar', 'USD', 'flags/IO.png', '#CC609F63'),
  ('IQ', 'Iraq', 'Baghdad', 'Asia', 'Arabic', 'ARA', 'Iraqi dinar', 'IQD', 'flags/IQ.png', '#CC5CAA83'),
  ('IR', 'Iran', 'Tehran', 'Asia', 'Persian (Farsi)', 'FAS', 'Iranian rial', 'IRR', 'flags/IR.png', '#CC5AB770'),
  ('IS', 'Iceland', 'Reykjavik', 'Europe', 'Icelandic', 'ISL', 'Icelandic króna', 'ISK', 'flags/IS.png', '#CC871321'),
  ('IT', 'Italy', 'Rome', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'flags/IT.png', '#CC55B683'),
  ('JE', 'Jersey', 'Saint Helier', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'flags/JE.png', '#CC6B5B5B'),
  ('JM', 'Jamaica', 'Kingston', 'North America', 'English', 'ENG', 'Jamaican dollar', 'JMD', 'flags/JM.png', '#CC77493E'),
  ('JO', 'Jordan', 'Amman', 'Asia', 'Arabic', 'ARA', 'Jordanian dinar', 'JOD', 'flags/JO.png', '#CC4B5B9A'),
  ('JP', 'Japan', 'Tokyo', 'Asia', 'Japanese', 'JPN', 'Japanese yen', 'JPY', 'flags/JP.png', '#CC87132F'),
  ('KE', 'Kenya', 'Nairobi', 'Africa', 'English', 'ENG', 'Kenyan shilling', 'KES', 'flags/KE.png', '#CC6E6C6C'),
  ('KG', 'Kyrgyzstan', 'Bishkek', 'Asia', 'Kyrgyz', 'KIR', 'Kyrgyzstani som', 'KGS', 'flags/KG.png', '#CC990099'),
  ('KH', 'Cambodia', 'Phnom Penh', 'Asia', 'Khmer', 'KHM', 'Cambodian riel', 'KHR', 'flags/KH.png', '#CC864D56'),
  ('KI', 'Kiribati', 'South Tarawa', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/KI.png', '#CC79A359'),
  ('KM', 'Comoros', 'Moroni', 'Africa', 'Arabic', 'ARA', 'Comorian franc', 'KMF', 'flags/KM.png', '#CC508D3D'),
  ('KN', 'Saint Kitts and Nevis', 'Basseterre', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/KN.png', '#CC73737A'),
  ('KP', 'North Korea', 'Pyongyang', 'Asia', 'Korean', 'KOR', 'North Korean won', 'KPW', 'flags/KP.png', '#CC8E0C11'),
  ('KR', 'South Korea', 'Seoul', 'Asia', 'Korean', 'KOR', 'South Korean won', 'KRW', 'flags/KR.png', '#CC7D7D7D'),
  ('KW', 'Kuwait', 'Kuwait City', 'Asia', 'Arabic', 'ARA', 'Kuwaiti dinar', 'KWD', 'flags/KW.png', '#CC461F7B'),
  ('KY', 'Cayman Islands', 'George Town', 'North America', 'English', 'ENG', 'Cayman Islands dollar', 'KYD', 'flags/KY.png', '#CC64998C'),
  ('KZ', 'Kazakhstan', 'Astana', 'Asia', 'Kazakh', 'KAZ', 'Kazakhstani tenge', 'KZT', 'flags/KZ.png', '#CC998C00'),
  ('LA', 'Laos', 'Vientiane', 'Asia', 'Lao', 'LAO', 'Lao kip', 'LAK', 'flags/LA.png', '#CC546F9A'),
  ('LB', 'Lebanon', 'Beirut', 'Asia', 'Arabic', 'ARA', 'Lebanese pound', 'LBP', 'flags/LB.png', '#CC4BAD76'),
  ('LC', 'Saint Lucia', 'Castries', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/LC.png', '#CC7B7B7B'),
  ('LI', 'Liechtenstein', 'Vaduz', 'Europe', 'German', 'DEU', 'Swiss franc', 'CHF', 'flags/LI.png', '#CC997B00'),
  ('LK', 'Sri Lanka', 'Sri Jayawardenepura Kotte', 'Asia', 'Sinhala', 'SIN', 'Sri Lankan rupee', 'LKR', 'flags/LK.png', '#CC996B00'),
  ('LR', 'Liberia', 'Monrovia', 'Africa', 'English', 'ENG', 'Liberian dollar', 'LRD', 'flags/LR.png', '#CC6E85A9'),
  ('LS', 'Lesotho', 'Maseru', 'Africa', 'English', 'ENG', 'Lesotho loti', 'LSL', 'flags/LS.png', '#CC858566'),
  ('LT', 'Lithuania', 'Vilnius', 'Europe', 'Lithuanian', 'LIT', 'Euro', 'EUR', 'flags/LT.png', '#CC986C02'),
  ('LU', 'Luxembourg', 'Luxembourg', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'flags/LU.png', '#CC196C81'),
  ('LV', 'Latvia', 'Riga', 'Europe', 'Latvian', 'LAV', 'Euro', 'EUR', 'flags/LV.png', '#CC7E1C2B'),
  ('LY', 'Libya', 'Tripoli', 'Africa', 'Arabic', 'ARA', 'Libyan dinar', 'LYD', 'flags/LY.png', '#CC929292'),
  ('MA', 'Morocco', 'Rabat', 'Africa', 'Arabic', 'ARA', 'Moroccan dirham', 'MAD', 'flags/MA.png', '#CC801A1E'),
  ('MC', 'Monaco', 'Monaco', 'Europe', 'French', 'FRA', 'Euro', 'EUR', 'flags/MC.png', '#CC8E0C1B'),
  ('MD', 'Moldova', 'Chișinău', 'Europe', 'Romanian', 'RON', 'Moldovan leu', 'MDL', 'flags/MD.png', '#CC549A6E'),
  ('ME', 'Montenegro', 'Podgorica', 'Europe', 'Montenegrin', 'CNR', 'Euro', 'EUR', 'flags/ME.png', '#CC795A49'),
  ('MF', 'Saint Martin', 'Marigot', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'flags/MF.png', '#CC566F8D'),
  ('MG', 'Madagascar', 'Antananarivo', 'Africa', 'French', 'FRA', 'Malagasy ariary', 'MGA', 'flags/MG.png', '#CC370397'),
  ('MH', 'Marshall Islands', 'Majuro', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'flags/MH.png', '#CC603268'),
  ('MK', 'North Macedonia', 'Skopje', 'Europe', 'Macedonian', 'MKD', 'denar', 'MKD', 'flags/MK.png', '#CC851518'),
  ('ML', 'Mali', 'Bamako', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/ML.png', '#CC987C02'),
  ('MM', 'Myanmar', 'Naypyidaw', 'Asia', 'Burmese', 'MYA', 'Burmese kyat', 'MMK', 'flags/MM.png', '#CCC2C797'),
  ('MN', 'Mongolia', 'Ulan Bator', 'Asia', 'Mongolian', 'MON', 'Mongolian tögrög', 'MNT', 'flags/MN.png', '#CC720496'),
  ('MO', 'Macau', 'None', 'Asia', 'Portuguese', 'POR', 'Macanese pataca', 'MOP', 'flags/MO.png', '#CC63A699'),
  ('MP', 'Northern Mariana Islands', 'Saipan', 'Oceania', 'Carolinian', 'CAL', 'United States dollar', 'USD', 'flags/MP.png', '#CC57838F'),
  ('MQ', 'Martinique', 'Fort-de-France', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'flags/MQ.png', '#CC944A63'),
  ('MR', 'Mauritania', 'Nouakchott', 'Africa', 'Arabic', 'ARA', 'Mauritanian ouguiya', 'MRU', 'flags/MR.png', '#CC5C6763'),
  ('MS', 'Montserrat', 'Plymouth', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/MS.png', '#CC6B9B58'),
  ('MT', 'Malta', 'Valletta', 'Europe', 'English', 'ENG', 'Euro', 'EUR', 'flags/MT.png', '#CCB85F6A'),
  ('MU', 'Mauritius', 'Port Louis', 'Africa', 'English', 'ENG', 'Mauritian rupee', 'MUR', 'flags/MU.png', '#CC298C0E'),
  ('MV', 'Maldives', 'Malé', 'Asia', 'Maldivian', 'DIV', 'Maldivian rufiyaa', 'MVR', 'flags/MV.png', '#CC71B791'),
  ('MW', 'Malawi', 'Lilongwe', 'Africa', 'English', 'ENG', 'Malawian kwacha', 'MWK', 'flags/MW.png', '#CC8E0C1B'),
  ('MX', 'Mexico', 'Mexico City', 'North America', 'Spanish', 'SPA', 'Mexican peso', 'MXN', 'flags/MX.png', '#CC549C9C'),
  ('MY', 'Malaysia', 'Kuala Lumpur', 'Asia', 'English', 'ENG', 'Malaysian ringgit', 'MYR', 'flags/MY.png', '#CC663366'),
  ('MZ', 'Mozambique', 'Maputo', 'Africa', 'Portuguese', 'POR', 'Mozambican metical', 'MZN', 'flags/MZ.png', '#CC8C877A'),
  ('NA', 'Namibia', 'Windhoek', 'Africa', 'Afrikaans', 'AFR', 'Namibian dollar', 'NAD', 'flags/NA.png', '#CCA5475F'),
  ('NC', 'New Caledonia', 'Nouméa', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'flags/NC.png', '#CC6E9084'),
  ('NE', 'Niger', 'Niamey', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/NE.png', '#CC963704'),
  ('NF', 'Norfolk Island', 'Kingston', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/NF.png', '#CC5DAA7E'),
  ('NG', 'Nigeria', 'Abuja', 'Africa', 'English', 'ENG', 'Nigerian naira', 'NGN', 'flags/NG.png', '#CC316953'),
  ('NI', 'Nicaragua', 'Managua', 'North America', 'Spanish', 'SPA', 'Nicaraguan córdoba', 'NIO', 'flags/NI.png', '#CC556B9C'),
  ('NL', 'Netherlands', 'Amsterdam', 'Europe', 'Dutch', 'NLD', 'Euro', 'EUR', 'flags/NL.png', '#CC84161F'),
  ('NO', 'Norway', 'Oslo', 'Europe', 'Norwegian Nynorsk', 'NNO', 'Norwegian krone', 'NOK', 'flags/NO.png', '#CC174083'),
  ('NP', 'Nepal', 'Kathmandu', 'Asia', 'Nepali', 'NEP', 'Nepalese rupee', 'NPR', 'flags/NP.png', '#CC47704C'),
  ('NR', 'Nauru', 'Yaren', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/NR.png', '#CC596E9D'),
  ('NU', 'Niue', 'Alofi', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'flags/NU.png', '#CC568D3F'),
  ('NZ', 'New Zealand', 'Wellington', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'flags/NZ.png', '#CC566B9B'),
  ('OM', 'Oman', 'Muscat', 'Asia', 'Arabic', 'ARA', 'Omani rial', 'OMR', 'flags/OM.png', '#CC431684'),
  ('PA', 'Panama', 'Panama City', 'North America', 'Spanish', 'SPA', 'Panamanian balboa', 'PAB', 'flags/PA.png', '#CC576A8D'),
  ('PE', 'Peru', 'Lima', 'South America', 'Aymara', 'AYM', 'Peruvian sol', 'PEN', 'flags/PE.png', '#CC8F0B17'),
  ('PF', 'French Polynesia', 'Papeetē', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'flags/PF.png', '#CCA2686D'),
  ('PG', 'Papua New Guinea', 'Port Moresby', 'Oceania', 'English', 'ENG', 'Papua New Guinean kina', 'PGK', 'flags/PG.png', '#CC727272'),
  ('PH', 'Philippines', 'Manila', 'Asia', 'English', 'ENG', 'Philippine peso', 'PHP', 'flags/PH.png', '#CC987C02'),
  ('PK', 'Pakistan', 'Islamabad', 'Asia', 'English', 'ENG', 'Pakistani rupee', 'PKR', 'flags/PK.png', '#CC59836B'),
  ('PL', 'Poland', 'Warsaw', 'Europe', 'Polish', 'POL', 'Polish złoty', 'PLN', 'flags/PL.png', '#CC8D0D27'),
  ('PM', 'Saint Pierre and Miquelon', 'Saint-Pierre', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'flags/PM.png', '#CC719F80'),
  ('PN', 'Pitcairn Islands', 'Adamstown', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'flags/PN.png', '#CC6B9B63'),
  ('PR', 'Puerto Rico', 'San Juan', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/PR.png', '#CC002999'),
  ('PS', 'Palestine', 'Ramallah', 'Asia', 'Arabic', 'ARA', 'Egyptian pound', 'EGP', 'flags/PS.png', '#CC8C8697'),
  ('PT', 'Portugal', 'Lisbon', 'Europe', 'Portuguese', 'POR', 'Euro', 'EUR', 'flags/PT.png', '#CCA7507A'),
  ('PW', 'Palau', 'Ngerulmud', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'flags/PW.png', '#CC95057B'),
  ('PY', 'Paraguay', 'Asunción', 'South America', 'Guaraní', 'GRN', 'Paraguayan guaraní', 'PYG', 'flags/PY.png', '#CC74A887'),
  ('QA', 'Qatar', 'Doha', 'Asia', 'Arabic', 'ARA', 'Qatari riyal', 'QAR', 'flags/QA.png', '#CCAA546E'),
  ('RE', 'Réunion', 'Saint-Denis', 'Africa', 'French', 'FRA', 'Euro', 'EUR', 'flags/RE.png', '#CC99AB60'),
  ('RO', 'Romania', 'Bucharest', 'Europe', 'Romanian', 'RON', 'Romanian leu', 'RON', 'flags/RO.png', '#CC54625B'),
  ('RS', 'Serbia', 'Belgrade', 'Europe', 'Serbian', 'SRP', 'Serbian dinar', 'RSD', 'flags/RS.png', '#CCA35C5D'),
  ('RU', 'Russia', 'Moscow', 'Europe', 'Russian', 'RUS', 'Russian ruble', 'RUB', 'flags/RU.png', '#CC1B617F'),
  ('RW', 'Rwanda', 'Kigali', 'Africa', 'English', 'ENG', 'Rwandan franc', 'RWF', 'flags/RW.png', '#CC4DAC96'),
  ('SA', 'Saudi Arabia', 'Riyadh', 'Asia', 'Arabic', 'ARA', 'Saudi riyal', 'SAR', 'flags/SA.png', '#CC5C927B'),
  ('SB', 'Solomon Islands', 'Honiara', 'Oceania', 'English', 'ENG', 'Solomon Islands dollar', 'SBD', 'flags/SB.png', '#CC47768B'),
  ('SC', 'Seychelles', 'Victoria', 'Africa', 'Seychellois Creole', 'CRS', 'Seychellois rupee', 'SCR', 'flags/SC.png', '#CCA69850'),
  ('SD', 'Sudan', 'Khartoum', 'Africa', 'Arabic', 'ARA', 'Sudanese pound', 'SDG', 'flags/SD.png', '#CC62A579'),
  ('SE', 'Sweden', 'Stockholm', 'Europe', 'Swedish', 'SWE', 'Swedish krona', 'SEK', 'flags/SE.png', '#CC996C01'),
  ('SG', 'Singapore', 'Singapore', 'Asia', 'English', 'ENG', 'Singapore dollar', 'SGD', 'flags/SG.png', '#CC8E0C17'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Jamestown', 'Africa', 'English', 'ENG', 'Pound sterling', 'GBP', 'flags/SH.png', '#CC546B9D'),
  ('SI', 'Slovenia', 'Ljubljana', 'Europe', 'Slovene', 'SLV', 'Euro', 'EUR', 'flags/SI.png', '#CCAAAA56'),
  ('SJ', 'Svalbard and Jan Mayen', 'Longyearbyen', 'Europe', 'Norwegian', 'NOR', 'krone', 'NOK', 'flags/SJ.png', '#CC174083'),
  ('SK', 'Slovakia', 'Bratislava', 'Europe', 'Slovak', 'SLK', 'Euro', 'EUR', 'flags/SK.png', '#CC5D3B74'),
  ('SL', 'Sierra Leone', 'Freetown', 'Africa', 'English', 'ENG', 'Leone', 'SLE', 'flags/SL.png', '#CC16842B'),
  ('SM', 'San Marino', 'City of San Marino', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'flags/SM.png', '#CC7AA065'),
  ('SN', 'Senegal', 'Dakar', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/SN.png', '#CC410F8B'),
  ('SO', 'Somalia', 'Mogadishu', 'Africa', 'Arabic', 'ARA', 'Somali shilling', 'SOS', 'flags/SO.png', '#CC174D83'),
  ('SR', 'Suriname', 'Paramaribo', 'South America', 'Dutch', 'NLD', 'Surinamese dollar', 'SRD', 'flags/SR.png', '#CC377E3F'),
  ('SS', 'South Sudan', 'Juba', 'Africa', 'English', 'ENG', 'South Sudanese pound', 'SSP', 'flags/SS.png', '#CC6B9872'),
  ('ST', 'São Tomé and Príncipe', 'São Tomé', 'Africa', 'Portuguese', 'POR', 'São Tomé and Príncipe dobra', 'STN', 'flags/ST.png', '#CC8E9277'),
  ('SV', 'El Salvador', 'San Salvador', 'North America', 'Spanish', 'SPA', 'United States dollar', 'USD', 'flags/SV.png', '#CC5С8996'),
  ('SX', 'Sint Maarten', 'Philipsburg', 'North America', 'English', 'ENG', 'Netherlands Antillean guilder', 'ANG', 'flags/SX.png', '#CC5873A6'),
  ('SY', 'Syria', 'Damascus', 'Asia', 'Arabic', 'ARA', 'Syrian pound', 'SYP', 'flags/SY.png', '#CC3D1387'),
  ('SZ', 'Eswatini', 'Mbabane', 'Africa', 'English', 'ENG', 'Swazi lilangeni', 'SZL', 'flags/SZ.png', '#CC3E4E8C'),
  ('TC', 'Turks and Caicos Islands', 'Cockburn Town', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/TC.png', '#CC556F9B'),
  ('TD', 'Chad', 'N''Djamena', 'Africa', 'Arabic', 'ARA', 'Central African CFA franc', 'XAF', 'flags/TD.png', '#CC499109'),
  ('TG', 'Togo', 'Lomé', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'flags/TG.png', '#CC7F9240'),
  ('TH', 'Thailand', 'Bangkok', 'Asia', 'Thai', 'THA', 'Thai baht', 'THB', 'flags/TH.png', '#CC851528'),
  ('TJ', 'Tajikistan', 'Dushanbe', 'Asia', 'Russian', 'RUS', 'Tajikistani somoni', 'TJS', 'flags/TJ.png', '#CC967604'),
  ('TK', 'Tokelau', 'Fakaofo', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'flags/TK.png', '#CC5C914D'),
  ('TL', 'Timor-Leste', 'Dili', 'Oceania', 'Portuguese', 'POR', 'United States dollar', 'USD', 'flags/TL.png', '#CC838383'),
  ('TM', 'Turkmenistan', 'Ashgabat', 'Asia', 'Russian', 'RUS', 'Turkmenistan manat', 'TMT', 'flags/TM.png', '#CC5AAB7B'),
  ('TN', 'Tunisia', 'Tunis', 'Africa', 'Arabic', 'ARA', 'Tunisian dinar', 'TND', 'flags/TN.png', '#CC8D0D18'),
  ('TO', 'Tonga', 'Nuku''alofa', 'Oceania', 'English', 'ENG', 'Tongan paʻanga', 'TOP', 'flags/TO.png', '#CC7B1F1F'),
  ('TR', 'Turkey', 'Ankara', 'Europe', 'Turkish', 'TUR', 'Turkish lira', 'TRY', 'flags/TR.png', '#CC93070F'),
  ('TT', 'Trinidad and Tobago', 'Port of Spain', 'North America', 'English', 'ENG', 'Trinidad and Tobago dollar', 'TTD', 'flags/TT.png', '#CC808080'),
  ('TV', 'Tuvalu', 'Funafuti', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'flags/TV.png', '#CCA3C59C'),
  ('TW', 'Taiwan', 'Taipei', 'Asia', 'Chinese', 'ZHO', 'New Taiwan dollar', 'TWD', 'flags/TW.png', '#CC992D01'),
  ('TZ', 'Tanzania', 'Dodoma', 'Africa', 'English', 'ENG', 'Tanzanian shilling', 'TZS', 'flags/TZ.png', '#CC6DB887'),
  ('UA', 'Ukraine', 'Kyiv', 'Europe', 'Ukrainian', 'UKR', 'Ukrainian hryvnia', 'UAH', 'flags/UA.png', '#CC985D5B'),
  ('UG', 'Uganda', 'Kampala', 'Africa', 'English', 'ENG', 'Ugandan shilling', 'UGX', 'flags/UG.png', '#CC964846'),
  ('UM', 'United States Minor Outlying Islands', 'Washington DC', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'flags/UM.png', '#CC6C84A0'),
  ('US', 'United States', 'Washington, D.C.', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/US.png', '#CC6C84A0'),
  ('UY', 'Uruguay', 'Montevideo', 'South America', 'Spanish', 'SPA', 'Uruguayan peso', 'UYU', 'flags/UY.png', '#CCAE8653'),
  ('UZ', 'Uzbekistan', 'Tashkent', 'Asia', 'Russian', 'RUS', 'Uzbekistani soʻm', 'UZS', 'flags/UZ.png', '#CC8F0B1A'),
  ('VA', 'Vatican City', 'Vatican City', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'flags/VA.png', '#CC7D4E92'),
  ('VC', 'Saint Vincent and the Grenadines', 'Kingstown', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'flags/VC.png', '#CC977903'),
  ('VE', 'Venezuela', 'Caracas', 'South America', 'Spanish', 'SPA', 'Venezuelan bolívar soberano', 'VES', 'flags/VE.png', '#CC558C0E'),
  ('VG', 'British Virgin Islands', 'Road Town', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/VG.png', '#CC5C7494'),
  ('VI', 'United States Virgin Islands', 'Charlotte Amalie', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'flags/VI.png', '#CC8B6258'),
  ('VN', 'Vietnam', 'Hanoi', 'Asia', 'Vietnamese', 'VIE', 'Vietnamese đồng', 'VND', 'flags/VN.png', '#CC990099'),
  ('VU', 'Vanuatu', 'Port Vila', 'Oceania', 'Bislama', 'BIS', 'Vanuatu vatu', 'VUV', 'flags/VU.png', '#CC3D7936'),
  ('WF', 'Wallis and Futuna', 'Mata-Utu', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'flags/WF.png', '#CC556E8D'),
  ('WS', 'Samoa', 'Apia', 'Oceania', 'English', 'ENG', 'Samoan tālā', 'WST', 'flags/WS.png', '#CC6982B4'),
  ('XK', 'Kosovo', 'Pristina', 'Europe', 'Albanian', 'SQI', 'Euro', 'EUR', 'flags/XK.png', '#CC9E8B68'),
  ('YE', 'Yemen', 'Sana''a', 'Asia', 'Arabic', 'ARA', 'Yemeni rial', 'YER', 'flags/YE.png', '#CC8E0C1B'),
  ('YT', 'Mayotte', 'Mamoudzou', 'Africa', 'French', 'FRA', 'Euro', 'EUR', 'flags/YT.png', '#CC848384'),
  ('ZA', 'South Africa', 'Pretoria', 'Africa', 'Afrikaans', 'AFR', 'South African rand', 'ZAR', 'flags/ZA.png', '#CC58A687'),
  ('ZM', 'Zambia', 'Lusaka', 'Africa', 'English', 'ENG', 'Zambian kwacha', 'ZMW', 'flags/ZM.png', '#CCA35A78'),
  ('ZW', 'Zimbabwe', 'Harare', 'Africa', 'Chibarwe', 'BWG', 'Zimbabwean dollar', 'ZWL', 'flags/ZW.png', '#CC408064')
on conflict (iso2) do update set
  name = excluded.name,
  capital = excluded.capital,
  continent = excluded.continent,
  primary_language = excluded.primary_language,
  primary_language_code = excluded.primary_language_code,
  primary_currency = excluded.primary_currency,
  primary_currency_code = excluded.primary_currency_code,
  flag_full_patch = excluded.flag_full_patch,
  background_hex = excluded.background_hex;
