-- THIS FILE IS GENERATED. Edit seeds_generators/countriesgenerator.py instead of this file.
insert into public.countries (
  iso2,
  name,
  capital,
  continent,
  primary_language,
  primary_language_code,
  primary_currency,
  primary_currency_code,
  flag_url
) values
  ('AD', 'Andorra', 'Andorra la Vella', 'Europe', 'Catalan', 'CAT', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AD.png'),
  ('AE', 'United Arab Emirates', 'Abu Dhabi', 'Asia', 'Arabic', 'ARA', 'United Arab Emirates dirham', 'AED', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AE.png'),
  ('AF', 'Afghanistan', 'Kabul', 'Asia', 'Dari', 'PRS', 'Afghan afghani', 'AFN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AF.png'),
  ('AG', 'Antigua and Barbuda', 'Saint John''s', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AG.png'),
  ('AI', 'Anguilla', 'The Valley', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AI.png'),
  ('AL', 'Albania', 'Tirana', 'Europe', 'Albanian', 'SQI', 'Albanian lek', 'ALL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AL.png'),
  ('AM', 'Armenia', 'Yerevan', 'Asia', 'Armenian', 'HYE', 'Armenian dram', 'AMD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AM.png'),
  ('AO', 'Angola', 'Luanda', 'Africa', 'Portuguese', 'POR', 'Angolan kwanza', 'AOA', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AO.png'),
  ('AR', 'Argentina', 'Buenos Aires', 'South America', 'Guaraní', 'GRN', 'Argentine peso', 'ARS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AR.png'),
  ('AS', 'American Samoa', 'Pago Pago', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AS.png'),
  ('AT', 'Austria', 'Vienna', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AT.png'),
  ('AU', 'Australia', 'Canberra', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AU.png'),
  ('AW', 'Aruba', 'Oranjestad', 'North America', 'Dutch', 'NLD', 'Aruban florin', 'AWG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AW.png'),
  ('AX', 'Åland Islands', 'Mariehamn', 'Europe', 'Swedish', 'SWE', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AX.png'),
  ('AZ', 'Azerbaijan', 'Baku', 'Europe', 'Azerbaijani', 'AZE', 'Azerbaijani manat', 'AZN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/AZ.png'),
  ('BA', 'Bosnia and Herzegovina', 'Sarajevo', 'Europe', 'Bosnian', 'BOS', 'Bosnia and Herzegovina convertible mark', 'BAM', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BA.png'),
  ('BB', 'Barbados', 'Bridgetown', 'North America', 'English', 'ENG', 'Barbadian dollar', 'BBD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BB.png'),
  ('BD', 'Bangladesh', 'Dhaka', 'Asia', 'Bengali', 'BEN', 'Bangladeshi taka', 'BDT', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BD.png'),
  ('BE', 'Belgium', 'Brussels', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BE.png'),
  ('BF', 'Burkina Faso', 'Ouagadougou', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BF.png'),
  ('BG', 'Bulgaria', 'Sofia', 'Europe', 'Bulgarian', 'BUL', 'Bulgarian lev', 'BGN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BG.png'),
  ('BH', 'Bahrain', 'Manama', 'Asia', 'Arabic', 'ARA', 'Bahraini dinar', 'BHD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BH.png'),
  ('BI', 'Burundi', 'Gitega', 'Africa', 'French', 'FRA', 'Burundian franc', 'BIF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BI.png'),
  ('BJ', 'Benin', 'Porto-Novo', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BJ.png'),
  ('BL', 'Saint Barthélemy', 'Gustavia', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BL.png'),
  ('BM', 'Bermuda', 'Hamilton', 'North America', 'English', 'ENG', 'Bermudian dollar', 'BMD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BM.png'),
  ('BN', 'Brunei', 'Bandar Seri Begawan', 'Asia', 'Malay', 'MSA', 'Brunei dollar', 'BND', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BN.png'),
  ('BO', 'Bolivia', 'Sucre', 'South America', 'Aymara', 'AYM', 'Bolivian boliviano', 'BOB', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BO.png'),
  ('BQ', 'Caribbean Netherlands', 'Kralendijk', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BQ.png'),
  ('BR', 'Brazil', 'Brasília', 'South America', 'Portuguese', 'POR', 'Brazilian real', 'BRL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BR.png'),
  ('BS', 'Bahamas', 'Nassau', 'North America', 'English', 'ENG', 'Bahamian dollar', 'BSD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BS.png'),
  ('BT', 'Bhutan', 'Thimphu', 'Asia', 'Dzongkha', 'DZO', 'Bhutanese ngultrum', 'BTN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BT.png'),
  ('BW', 'Botswana', 'Gaborone', 'Africa', 'English', 'ENG', 'Botswana pula', 'BWP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BW.png'),
  ('BY', 'Belarus', 'Minsk', 'Europe', 'Belarusian', 'BEL', 'Belarusian ruble', 'BYN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BY.png'),
  ('BZ', 'Belize', 'Belmopan', 'North America', 'Belizean Creole', 'BJZ', 'Belize dollar', 'BZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/BZ.png'),
  ('CA', 'Canada', 'Ottawa', 'North America', 'English', 'ENG', 'Canadian dollar', 'CAD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CA.png'),
  ('CC', 'Cocos (Keeling) Islands', 'West Island', 'Asia', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CC.png'),
  ('CD', 'DR Congo', 'Kinshasa', 'Africa', 'French', 'FRA', 'Congolese franc', 'CDF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CD.png'),
  ('CF', 'Central African Republic', 'Bangui', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CF.png'),
  ('CG', 'Republic of the Congo', 'Brazzaville', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CG.png'),
  ('CH', 'Switzerland', 'Bern', 'Europe', 'French', 'FRA', 'Swiss franc', 'CHF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CH.png'),
  ('CI', 'Ivory Coast', 'Yamoussoukro', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CI.png'),
  ('CK', 'Cook Islands', 'Avarua', 'Oceania', 'English', 'ENG', 'Cook Islands dollar', 'CKD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CK.png'),
  ('CL', 'Chile', 'Santiago', 'South America', 'Spanish', 'SPA', 'Chilean peso', 'CLP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CL.png'),
  ('CM', 'Cameroon', 'Yaoundé', 'Africa', 'English', 'ENG', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CM.png'),
  ('CN', 'China', 'Beijing', 'Asia', 'Chinese', 'ZHO', 'Chinese yuan', 'CNY', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CN.png'),
  ('CO', 'Colombia', 'Bogotá', 'South America', 'Spanish', 'SPA', 'Colombian peso', 'COP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CO.png'),
  ('CR', 'Costa Rica', 'San José', 'North America', 'Spanish', 'SPA', 'Costa Rican colón', 'CRC', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CR.png'),
  ('CU', 'Cuba', 'Havana', 'North America', 'Spanish', 'SPA', 'Cuban convertible peso', 'CUC', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CU.png'),
  ('CV', 'Cape Verde', 'Praia', 'Africa', 'Portuguese', 'POR', 'Cape Verdean escudo', 'CVE', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CV.png'),
  ('CW', 'Curaçao', 'Willemstad', 'North America', 'English', 'ENG', 'Netherlands Antillean guilder', 'ANG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CW.png'),
  ('CX', 'Christmas Island', 'Flying Fish Cove', 'Asia', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CX.png'),
  ('CY', 'Cyprus', 'Nicosia', 'Europe', 'Greek', 'ELL', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CY.png'),
  ('CZ', 'Czechia', 'Prague', 'Europe', 'Czech', 'CES', 'Czech koruna', 'CZK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/CZ.png'),
  ('DE', 'Germany', 'Berlin', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DE.png'),
  ('DJ', 'Djibouti', 'Djibouti', 'Africa', 'Arabic', 'ARA', 'Djiboutian franc', 'DJF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DJ.png'),
  ('DK', 'Denmark', 'Copenhagen', 'Europe', 'Danish', 'DAN', 'Danish krone', 'DKK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DK.png'),
  ('DM', 'Dominica', 'Roseau', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DM.png'),
  ('DO', 'Dominican Republic', 'Santo Domingo', 'North America', 'Spanish', 'SPA', 'Dominican peso', 'DOP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DO.png'),
  ('DZ', 'Algeria', 'Algiers', 'Africa', 'Arabic', 'ARA', 'Algerian dinar', 'DZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/DZ.png'),
  ('EC', 'Ecuador', 'Quito', 'South America', 'Spanish', 'SPA', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/EC.png'),
  ('EE', 'Estonia', 'Tallinn', 'Europe', 'Estonian', 'EST', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/EE.png'),
  ('EG', 'Egypt', 'Cairo', 'Africa', 'Arabic', 'ARA', 'Egyptian pound', 'EGP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/EG.png'),
  ('EH', 'Western Sahara', 'El Aaiún', 'Africa', 'Berber', 'BER', 'Algerian dinar', 'DZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/EH.png'),
  ('ER', 'Eritrea', 'Asmara', 'Africa', 'Arabic', 'ARA', 'Eritrean nakfa', 'ERN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ER.png'),
  ('ES', 'Spain', 'Madrid', 'Europe', 'Spanish', 'SPA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ES.png'),
  ('ET', 'Ethiopia', 'Addis Ababa', 'Africa', 'Amharic', 'AMH', 'Ethiopian birr', 'ETB', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ET.png'),
  ('FI', 'Finland', 'Helsinki', 'Europe', 'Finnish', 'FIN', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FI.png'),
  ('FJ', 'Fiji', 'Suva', 'Oceania', 'English', 'ENG', 'Fijian dollar', 'FJD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FJ.png'),
  ('FK', 'Falkland Islands', 'Stanley', 'South America', 'English', 'ENG', 'Falkland Islands pound', 'FKP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FK.png'),
  ('FM', 'Micronesia', 'Palikir', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FM.png'),
  ('FO', 'Faroe Islands', 'Tórshavn', 'Europe', 'Danish', 'DAN', 'Danish krone', 'DKK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FO.png'),
  ('FR', 'France', 'Paris', 'Europe', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/FR.png'),
  ('GA', 'Gabon', 'Libreville', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GA.png'),
  ('GB', 'United Kingdom', 'London', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GB.png'),
  ('GD', 'Grenada', 'St. George''s', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GD.png'),
  ('GE', 'Georgia', 'Tbilisi', 'Asia', 'Georgian', 'KAT', 'lari', 'GEL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GE.png'),
  ('GF', 'French Guiana', 'Cayenne', 'South America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GF.png'),
  ('GG', 'Guernsey', 'St. Peter Port', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GG.png'),
  ('GH', 'Ghana', 'Accra', 'Africa', 'English', 'ENG', 'Ghanaian cedi', 'GHS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GH.png'),
  ('GI', 'Gibraltar', 'Gibraltar', 'Europe', 'English', 'ENG', 'Gibraltar pound', 'GIP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GI.png'),
  ('GL', 'Greenland', 'Nuuk', 'North America', 'Greenlandic', 'KAL', 'krone', 'DKK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GL.png'),
  ('GM', 'Gambia', 'Banjul', 'Africa', 'English', 'ENG', 'dalasi', 'GMD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GM.png'),
  ('GN', 'Guinea', 'Conakry', 'Africa', 'French', 'FRA', 'Guinean franc', 'GNF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GN.png'),
  ('GP', 'Guadeloupe', 'Basse-Terre', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GP.png'),
  ('GQ', 'Equatorial Guinea', 'Malabo', 'Africa', 'French', 'FRA', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GQ.png'),
  ('GR', 'Greece', 'Athens', 'Europe', 'Greek', 'ELL', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GR.png'),
  ('GT', 'Guatemala', 'Guatemala City', 'North America', 'Spanish', 'SPA', 'Guatemalan quetzal', 'GTQ', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GT.png'),
  ('GU', 'Guam', 'Hagåtña', 'Oceania', 'Chamorro', 'CHA', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GU.png'),
  ('GW', 'Guinea-Bissau', 'Bissau', 'Africa', 'Portuguese', 'POR', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GW.png'),
  ('GY', 'Guyana', 'Georgetown', 'South America', 'English', 'ENG', 'Guyanese dollar', 'GYD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/GY.png'),
  ('HK', 'Hong Kong', 'City of Victoria', 'Asia', 'English', 'ENG', 'Hong Kong dollar', 'HKD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/HK.png'),
  ('HN', 'Honduras', 'Tegucigalpa', 'North America', 'Spanish', 'SPA', 'Honduran lempira', 'HNL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/HN.png'),
  ('HR', 'Croatia', 'Zagreb', 'Europe', 'Croatian', 'HRV', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/HR.png'),
  ('HT', 'Haiti', 'Port-au-Prince', 'North America', 'French', 'FRA', 'Haitian gourde', 'HTG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/HT.png'),
  ('HU', 'Hungary', 'Budapest', 'Europe', 'Hungarian', 'HUN', 'Hungarian forint', 'HUF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/HU.png'),
  ('ID', 'Indonesia', 'Jakarta', 'Asia', 'Indonesian', 'IND', 'Indonesian rupiah', 'IDR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ID.png'),
  ('IE', 'Ireland', 'Dublin', 'Europe', 'English', 'ENG', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IE.png'),
  ('IL', 'Israel', 'Jerusalem', 'Asia', 'Arabic', 'ARA', 'Israeli new shekel', 'ILS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IL.png'),
  ('IM', 'Isle of Man', 'Douglas', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IM.png'),
  ('IN', 'India', 'New Delhi', 'Asia', 'English', 'ENG', 'Indian rupee', 'INR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IN.png'),
  ('IO', 'British Indian Ocean Territory', 'Diego Garcia', 'Asia', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IO.png'),
  ('IQ', 'Iraq', 'Baghdad', 'Asia', 'Arabic', 'ARA', 'Iraqi dinar', 'IQD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IQ.png'),
  ('IR', 'Iran', 'Tehran', 'Asia', 'Persian (Farsi)', 'FAS', 'Iranian rial', 'IRR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IR.png'),
  ('IS', 'Iceland', 'Reykjavik', 'Europe', 'Icelandic', 'ISL', 'Icelandic króna', 'ISK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IS.png'),
  ('IT', 'Italy', 'Rome', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/IT.png'),
  ('JE', 'Jersey', 'Saint Helier', 'Europe', 'English', 'ENG', 'British pound', 'GBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/JE.png'),
  ('JM', 'Jamaica', 'Kingston', 'North America', 'English', 'ENG', 'Jamaican dollar', 'JMD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/JM.png'),
  ('JO', 'Jordan', 'Amman', 'Asia', 'Arabic', 'ARA', 'Jordanian dinar', 'JOD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/JO.png'),
  ('JP', 'Japan', 'Tokyo', 'Asia', 'Japanese', 'JPN', 'Japanese yen', 'JPY', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/JP.png'),
  ('KE', 'Kenya', 'Nairobi', 'Africa', 'English', 'ENG', 'Kenyan shilling', 'KES', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KE.png'),
  ('KG', 'Kyrgyzstan', 'Bishkek', 'Asia', 'Kyrgyz', 'KIR', 'Kyrgyzstani som', 'KGS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KG.png'),
  ('KH', 'Cambodia', 'Phnom Penh', 'Asia', 'Khmer', 'KHM', 'Cambodian riel', 'KHR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KH.png'),
  ('KI', 'Kiribati', 'South Tarawa', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KI.png'),
  ('KM', 'Comoros', 'Moroni', 'Africa', 'Arabic', 'ARA', 'Comorian franc', 'KMF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KM.png'),
  ('KN', 'Saint Kitts and Nevis', 'Basseterre', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KN.png'),
  ('KP', 'North Korea', 'Pyongyang', 'Asia', 'Korean', 'KOR', 'North Korean won', 'KPW', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KP.png'),
  ('KR', 'South Korea', 'Seoul', 'Asia', 'Korean', 'KOR', 'South Korean won', 'KRW', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KR.png'),
  ('KW', 'Kuwait', 'Kuwait City', 'Asia', 'Arabic', 'ARA', 'Kuwaiti dinar', 'KWD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KW.png'),
  ('KY', 'Cayman Islands', 'George Town', 'North America', 'English', 'ENG', 'Cayman Islands dollar', 'KYD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KY.png'),
  ('KZ', 'Kazakhstan', 'Astana', 'Asia', 'Kazakh', 'KAZ', 'Kazakhstani tenge', 'KZT', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/KZ.png'),
  ('LA', 'Laos', 'Vientiane', 'Asia', 'Lao', 'LAO', 'Lao kip', 'LAK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LA.png'),
  ('LB', 'Lebanon', 'Beirut', 'Asia', 'Arabic', 'ARA', 'Lebanese pound', 'LBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LB.png'),
  ('LC', 'Saint Lucia', 'Castries', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LC.png'),
  ('LI', 'Liechtenstein', 'Vaduz', 'Europe', 'German', 'DEU', 'Swiss franc', 'CHF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LI.png'),
  ('LK', 'Sri Lanka', 'Sri Jayawardenepura Kotte', 'Asia', 'Sinhala', 'SIN', 'Sri Lankan rupee', 'LKR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LK.png'),
  ('LR', 'Liberia', 'Monrovia', 'Africa', 'English', 'ENG', 'Liberian dollar', 'LRD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LR.png'),
  ('LS', 'Lesotho', 'Maseru', 'Africa', 'English', 'ENG', 'Lesotho loti', 'LSL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LS.png'),
  ('LT', 'Lithuania', 'Vilnius', 'Europe', 'Lithuanian', 'LIT', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LT.png'),
  ('LU', 'Luxembourg', 'Luxembourg', 'Europe', 'German', 'DEU', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LU.png'),
  ('LV', 'Latvia', 'Riga', 'Europe', 'Latvian', 'LAV', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LV.png'),
  ('LY', 'Libya', 'Tripoli', 'Africa', 'Arabic', 'ARA', 'Libyan dinar', 'LYD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/LY.png'),
  ('MA', 'Morocco', 'Rabat', 'Africa', 'Arabic', 'ARA', 'Moroccan dirham', 'MAD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MA.png'),
  ('MC', 'Monaco', 'Monaco', 'Europe', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MC.png'),
  ('MD', 'Moldova', 'Chișinău', 'Europe', 'Romanian', 'RON', 'Moldovan leu', 'MDL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MD.png'),
  ('ME', 'Montenegro', 'Podgorica', 'Europe', 'Montenegrin', 'CNR', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ME.png'),
  ('MF', 'Saint Martin', 'Marigot', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MF.png'),
  ('MG', 'Madagascar', 'Antananarivo', 'Africa', 'French', 'FRA', 'Malagasy ariary', 'MGA', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MG.png'),
  ('MH', 'Marshall Islands', 'Majuro', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MH.png'),
  ('MK', 'North Macedonia', 'Skopje', 'Europe', 'Macedonian', 'MKD', 'denar', 'MKD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MK.png'),
  ('ML', 'Mali', 'Bamako', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ML.png'),
  ('MM', 'Myanmar', 'Naypyidaw', 'Asia', 'Burmese', 'MYA', 'Burmese kyat', 'MMK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MM.png'),
  ('MN', 'Mongolia', 'Ulan Bator', 'Asia', 'Mongolian', 'MON', 'Mongolian tögrög', 'MNT', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MN.png'),
  ('MO', 'Macau', 'None', 'Asia', 'Portuguese', 'POR', 'Macanese pataca', 'MOP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MO.png'),
  ('MP', 'Northern Mariana Islands', 'Saipan', 'Oceania', 'Carolinian', 'CAL', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MP.png'),
  ('MQ', 'Martinique', 'Fort-de-France', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MQ.png'),
  ('MR', 'Mauritania', 'Nouakchott', 'Africa', 'Arabic', 'ARA', 'Mauritanian ouguiya', 'MRU', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MR.png'),
  ('MS', 'Montserrat', 'Plymouth', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MS.png'),
  ('MT', 'Malta', 'Valletta', 'Europe', 'English', 'ENG', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MT.png'),
  ('MU', 'Mauritius', 'Port Louis', 'Africa', 'English', 'ENG', 'Mauritian rupee', 'MUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MU.png'),
  ('MV', 'Maldives', 'Malé', 'Asia', 'Maldivian', 'DIV', 'Maldivian rufiyaa', 'MVR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MV.png'),
  ('MW', 'Malawi', 'Lilongwe', 'Africa', 'English', 'ENG', 'Malawian kwacha', 'MWK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MW.png'),
  ('MX', 'Mexico', 'Mexico City', 'North America', 'Spanish', 'SPA', 'Mexican peso', 'MXN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MX.png'),
  ('MY', 'Malaysia', 'Kuala Lumpur', 'Asia', 'English', 'ENG', 'Malaysian ringgit', 'MYR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MY.png'),
  ('MZ', 'Mozambique', 'Maputo', 'Africa', 'Portuguese', 'POR', 'Mozambican metical', 'MZN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/MZ.png'),
  ('NA', 'Namibia', 'Windhoek', 'Africa', 'Afrikaans', 'AFR', 'Namibian dollar', 'NAD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NA.png'),
  ('NC', 'New Caledonia', 'Nouméa', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NC.png'),
  ('NE', 'Niger', 'Niamey', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NE.png'),
  ('NF', 'Norfolk Island', 'Kingston', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NF.png'),
  ('NG', 'Nigeria', 'Abuja', 'Africa', 'English', 'ENG', 'Nigerian naira', 'NGN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NG.png'),
  ('NI', 'Nicaragua', 'Managua', 'North America', 'Spanish', 'SPA', 'Nicaraguan córdoba', 'NIO', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NI.png'),
  ('NL', 'Netherlands', 'Amsterdam', 'Europe', 'Dutch', 'NLD', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NL.png'),
  ('NO', 'Norway', 'Oslo', 'Europe', 'Norwegian Nynorsk', 'NNO', 'Norwegian krone', 'NOK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NO.png'),
  ('NP', 'Nepal', 'Kathmandu', 'Asia', 'Nepali', 'NEP', 'Nepalese rupee', 'NPR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NP.png'),
  ('NR', 'Nauru', 'Yaren', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NR.png'),
  ('NU', 'Niue', 'Alofi', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NU.png'),
  ('NZ', 'New Zealand', 'Wellington', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/NZ.png'),
  ('OM', 'Oman', 'Muscat', 'Asia', 'Arabic', 'ARA', 'Omani rial', 'OMR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/OM.png'),
  ('PA', 'Panama', 'Panama City', 'North America', 'Spanish', 'SPA', 'Panamanian balboa', 'PAB', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PA.png'),
  ('PE', 'Peru', 'Lima', 'South America', 'Aymara', 'AYM', 'Peruvian sol', 'PEN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PE.png'),
  ('PF', 'French Polynesia', 'Papeetē', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PF.png'),
  ('PG', 'Papua New Guinea', 'Port Moresby', 'Oceania', 'English', 'ENG', 'Papua New Guinean kina', 'PGK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PG.png'),
  ('PH', 'Philippines', 'Manila', 'Asia', 'English', 'ENG', 'Philippine peso', 'PHP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PH.png'),
  ('PK', 'Pakistan', 'Islamabad', 'Asia', 'English', 'ENG', 'Pakistani rupee', 'PKR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PK.png'),
  ('PL', 'Poland', 'Warsaw', 'Europe', 'Polish', 'POL', 'Polish złoty', 'PLN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PL.png'),
  ('PM', 'Saint Pierre and Miquelon', 'Saint-Pierre', 'North America', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PM.png'),
  ('PN', 'Pitcairn Islands', 'Adamstown', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PN.png'),
  ('PR', 'Puerto Rico', 'San Juan', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PR.png'),
  ('PS', 'Palestine', 'Ramallah', 'Asia', 'Arabic', 'ARA', 'Egyptian pound', 'EGP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PS.png'),
  ('PT', 'Portugal', 'Lisbon', 'Europe', 'Portuguese', 'POR', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PT.png'),
  ('PW', 'Palau', 'Ngerulmud', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PW.png'),
  ('PY', 'Paraguay', 'Asunción', 'South America', 'Guaraní', 'GRN', 'Paraguayan guaraní', 'PYG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/PY.png'),
  ('QA', 'Qatar', 'Doha', 'Asia', 'Arabic', 'ARA', 'Qatari riyal', 'QAR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/QA.png'),
  ('RE', 'Réunion', 'Saint-Denis', 'Africa', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/RE.png'),
  ('RO', 'Romania', 'Bucharest', 'Europe', 'Romanian', 'RON', 'Romanian leu', 'RON', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/RO.png'),
  ('RS', 'Serbia', 'Belgrade', 'Europe', 'Serbian', 'SRP', 'Serbian dinar', 'RSD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/RS.png'),
  ('RU', 'Russia', 'Moscow', 'Europe', 'Russian', 'RUS', 'Russian ruble', 'RUB', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/RU.png'),
  ('RW', 'Rwanda', 'Kigali', 'Africa', 'English', 'ENG', 'Rwandan franc', 'RWF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/RW.png'),
  ('SA', 'Saudi Arabia', 'Riyadh', 'Asia', 'Arabic', 'ARA', 'Saudi riyal', 'SAR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SA.png'),
  ('SB', 'Solomon Islands', 'Honiara', 'Oceania', 'English', 'ENG', 'Solomon Islands dollar', 'SBD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SB.png'),
  ('SC', 'Seychelles', 'Victoria', 'Africa', 'Seychellois Creole', 'CRS', 'Seychellois rupee', 'SCR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SC.png'),
  ('SD', 'Sudan', 'Khartoum', 'Africa', 'Arabic', 'ARA', 'Sudanese pound', 'SDG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SD.png'),
  ('SE', 'Sweden', 'Stockholm', 'Europe', 'Swedish', 'SWE', 'Swedish krona', 'SEK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SE.png'),
  ('SG', 'Singapore', 'Singapore', 'Asia', 'English', 'ENG', 'Singapore dollar', 'SGD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SG.png'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Jamestown', 'Africa', 'English', 'ENG', 'Pound sterling', 'GBP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SH.png'),
  ('SI', 'Slovenia', 'Ljubljana', 'Europe', 'Slovene', 'SLV', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SI.png'),
  ('SJ', 'Svalbard and Jan Mayen', 'Longyearbyen', 'Europe', 'Norwegian', 'NOR', 'krone', 'NOK', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SJ.png'),
  ('SK', 'Slovakia', 'Bratislava', 'Europe', 'Slovak', 'SLK', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SK.png'),
  ('SL', 'Sierra Leone', 'Freetown', 'Africa', 'English', 'ENG', 'Leone', 'SLE', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SL.png'),
  ('SM', 'San Marino', 'City of San Marino', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SM.png'),
  ('SN', 'Senegal', 'Dakar', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SN.png'),
  ('SO', 'Somalia', 'Mogadishu', 'Africa', 'Arabic', 'ARA', 'Somali shilling', 'SOS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SO.png'),
  ('SR', 'Suriname', 'Paramaribo', 'South America', 'Dutch', 'NLD', 'Surinamese dollar', 'SRD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SR.png'),
  ('SS', 'South Sudan', 'Juba', 'Africa', 'English', 'ENG', 'South Sudanese pound', 'SSP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SS.png'),
  ('ST', 'São Tomé and Príncipe', 'São Tomé', 'Africa', 'Portuguese', 'POR', 'São Tomé and Príncipe dobra', 'STN', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ST.png'),
  ('SV', 'El Salvador', 'San Salvador', 'North America', 'Spanish', 'SPA', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SV.png'),
  ('SX', 'Sint Maarten', 'Philipsburg', 'North America', 'English', 'ENG', 'Netherlands Antillean guilder', 'ANG', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SX.png'),
  ('SY', 'Syria', 'Damascus', 'Asia', 'Arabic', 'ARA', 'Syrian pound', 'SYP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SY.png'),
  ('SZ', 'Eswatini', 'Mbabane', 'Africa', 'English', 'ENG', 'Swazi lilangeni', 'SZL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/SZ.png'),
  ('TC', 'Turks and Caicos Islands', 'Cockburn Town', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TC.png'),
  ('TD', 'Chad', 'N''Djamena', 'Africa', 'Arabic', 'ARA', 'Central African CFA franc', 'XAF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TD.png'),
  ('TG', 'Togo', 'Lomé', 'Africa', 'French', 'FRA', 'West African CFA franc', 'XOF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TG.png'),
  ('TH', 'Thailand', 'Bangkok', 'Asia', 'Thai', 'THA', 'Thai baht', 'THB', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TH.png'),
  ('TJ', 'Tajikistan', 'Dushanbe', 'Asia', 'Russian', 'RUS', 'Tajikistani somoni', 'TJS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TJ.png'),
  ('TK', 'Tokelau', 'Fakaofo', 'Oceania', 'English', 'ENG', 'New Zealand dollar', 'NZD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TK.png'),
  ('TL', 'Timor-Leste', 'Dili', 'Oceania', 'Portuguese', 'POR', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TL.png'),
  ('TM', 'Turkmenistan', 'Ashgabat', 'Asia', 'Russian', 'RUS', 'Turkmenistan manat', 'TMT', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TM.png'),
  ('TN', 'Tunisia', 'Tunis', 'Africa', 'Arabic', 'ARA', 'Tunisian dinar', 'TND', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TN.png'),
  ('TO', 'Tonga', 'Nuku''alofa', 'Oceania', 'English', 'ENG', 'Tongan paʻanga', 'TOP', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TO.png'),
  ('TR', 'Turkey', 'Ankara', 'Europe', 'Turkish', 'TUR', 'Turkish lira', 'TRY', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TR.png'),
  ('TT', 'Trinidad and Tobago', 'Port of Spain', 'North America', 'English', 'ENG', 'Trinidad and Tobago dollar', 'TTD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TT.png'),
  ('TV', 'Tuvalu', 'Funafuti', 'Oceania', 'English', 'ENG', 'Australian dollar', 'AUD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TV.png'),
  ('TW', 'Taiwan', 'Taipei', 'Asia', 'Chinese', 'ZHO', 'New Taiwan dollar', 'TWD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TW.png'),
  ('TZ', 'Tanzania', 'Dodoma', 'Africa', 'English', 'ENG', 'Tanzanian shilling', 'TZS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/TZ.png'),
  ('UA', 'Ukraine', 'Kyiv', 'Europe', 'Ukrainian', 'UKR', 'Ukrainian hryvnia', 'UAH', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/UA.png'),
  ('UG', 'Uganda', 'Kampala', 'Africa', 'English', 'ENG', 'Ugandan shilling', 'UGX', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/UG.png'),
  ('UM', 'United States Minor Outlying Islands', 'Washington DC', 'Oceania', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/UM.png'),
  ('US', 'United States', 'Washington, D.C.', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/US.png'),
  ('UY', 'Uruguay', 'Montevideo', 'South America', 'Spanish', 'SPA', 'Uruguayan peso', 'UYU', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/UY.png'),
  ('UZ', 'Uzbekistan', 'Tashkent', 'Asia', 'Russian', 'RUS', 'Uzbekistani soʻm', 'UZS', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/UZ.png'),
  ('VA', 'Vatican City', 'Vatican City', 'Europe', 'Italian', 'ITA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VA.png'),
  ('VC', 'Saint Vincent and the Grenadines', 'Kingstown', 'North America', 'English', 'ENG', 'Eastern Caribbean dollar', 'XCD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VC.png'),
  ('VE', 'Venezuela', 'Caracas', 'South America', 'Spanish', 'SPA', 'Venezuelan bolívar soberano', 'VES', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VE.png'),
  ('VG', 'British Virgin Islands', 'Road Town', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VG.png'),
  ('VI', 'United States Virgin Islands', 'Charlotte Amalie', 'North America', 'English', 'ENG', 'United States dollar', 'USD', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VI.png'),
  ('VN', 'Vietnam', 'Hanoi', 'Asia', 'Vietnamese', 'VIE', 'Vietnamese đồng', 'VND', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VN.png'),
  ('VU', 'Vanuatu', 'Port Vila', 'Oceania', 'Bislama', 'BIS', 'Vanuatu vatu', 'VUV', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/VU.png'),
  ('WF', 'Wallis and Futuna', 'Mata-Utu', 'Oceania', 'French', 'FRA', 'CFP franc', 'XPF', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/WF.png'),
  ('WS', 'Samoa', 'Apia', 'Oceania', 'English', 'ENG', 'Samoan tālā', 'WST', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/WS.png'),
  ('XK', 'Kosovo', 'Pristina', 'Europe', 'Albanian', 'SQI', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/XK.png'),
  ('YE', 'Yemen', 'Sana''a', 'Asia', 'Arabic', 'ARA', 'Yemeni rial', 'YER', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/YE.png'),
  ('YT', 'Mayotte', 'Mamoudzou', 'Africa', 'French', 'FRA', 'Euro', 'EUR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/YT.png'),
  ('ZA', 'South Africa', 'Pretoria', 'Africa', 'Afrikaans', 'AFR', 'South African rand', 'ZAR', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ZA.png'),
  ('ZM', 'Zambia', 'Lusaka', 'Africa', 'English', 'ENG', 'Zambian kwacha', 'ZMW', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ZM.png'),
  ('ZW', 'Zimbabwe', 'Harare', 'Africa', 'Chibarwe', 'BWG', 'Zimbabwean dollar', 'ZWL', 'https://jlvsmfdazodotqecvkyt.supabase.co/storage/v1/object/public/flags/ZW.png')
on conflict (iso2) do update set
  name = excluded.name,
  capital = excluded.capital,
  continent = excluded.continent,
  primary_language = excluded.primary_language,
  primary_language_code = excluded.primary_language_code,
  primary_currency = excluded.primary_currency,
  primary_currency_code = excluded.primary_currency_code,
  flag_url = excluded.flag_url;
