"""LLM-based generator for country_overview table."""

from pathlib import Path
from typing import Dict, List
from urllib.parse import quote

from generators.base_generator import BaseGenerator
from utils.database.country_overview_repository import (
    CountryOverview,
    CountryOverviewRepository,
)
from utils.database.country_repository import Country, CountryRepository
from utils.openai.country_overview_assignment import (
    CountryOverviewAssignment,
    CountryOverviewAssignmentClient,
)
from utils.settings.voyager_settings import VoyagerSeedSettings


class CountryOverviewGenerator(BaseGenerator):
    """Generator for country_overview table using LLM."""

    filename = "06_country_overview.sql"

    def __init__(self, settings: VoyagerSeedSettings):
        """Initialize the generator.

        Args:
            settings: Voyager seed settings for configuration.
        """
        super().__init__(settings)
        self.country_repo = CountryRepository(settings)
        self.country_overview_repo = CountryOverviewRepository(settings)
        self.openai_client = CountryOverviewAssignmentClient(settings)
        print(
            f"[country_overview] Initialized with batch size: {CountryOverviewAssignmentClient.BATCH_SIZE}"
        )

    def _generate_wikipedia_url(self, country_name: str) -> str:
        """Generate Wikipedia search URL for a country.

        Args:
            country_name: Name of the country.

        Returns:
            Wikipedia search URL in format: https://en.wikipedia.org/wiki/Special:Search?search=<Country>
        """
        return f"https://en.wikipedia.org/wiki/Special:Search?search={quote(country_name)}"

    def generate(self, output_path: Path) -> None:
        """Generate country_overview records using LLM and write directly to database.

        This method:
        1. Fetches all countries from the database
        2. Processes countries in batches using OpenAI
        3. Writes results directly to the country_overview table

        Args:
            output_path: Path parameter (not used, as we write directly to DB).
        """
        print("[country_overview] Starting generation...")

        # Fetch all countries
        print("[country_overview] Fetching countries from database...")
        countries = self.country_repo.get_all()
        print(f"[country_overview] Found {len(countries)} countries")

        if not countries:
            print("[country_overview] No countries found in database, skipping generation")
            return

        # Create mappings of country ISO2 to country ID and country name
        country_iso2_to_id: Dict[str, str] = {
            country.iso2: country.id for country in countries
        }
        country_iso2_to_name: Dict[str, str] = {
            country.iso2: country.name for country in countries
        }

        # Process countries in batches
        batch_size = CountryOverviewAssignmentClient.BATCH_SIZE
        total_batches = (len(countries) + batch_size - 1) // batch_size
        print(
            f"[country_overview] Processing {len(countries)} countries in {total_batches} batch(es) of {batch_size}"
        )

        all_overview_records: List[CountryOverview] = []
        processed_countries = 0

        for batch_idx in range(0, len(countries), batch_size):
            batch_countries = countries[batch_idx : batch_idx + batch_size]
            batch_num = (batch_idx // batch_size) + 1

            print(
                f"[country_overview] Processing batch {batch_num}/{total_batches} ({len(batch_countries)} countries)..."
            )

            try:
                # Call OpenAI to get overviews for countries in this batch
                assignments = self.openai_client.get_overviews_for_countries(
                    batch_countries
                )

                # Convert assignments to CountryOverview records
                batch_records: List[CountryOverview] = []
                for assignment in assignments:
                    country_id = country_iso2_to_id.get(assignment.country_iso2)
                    country_name = country_iso2_to_name.get(assignment.country_iso2)
                    if not country_id:
                        print(
                            f"[country_overview] Warning: Country {assignment.country_iso2} not found in database, skipping"
                        )
                        continue

                    # Generate Wikipedia URL
                    wikipedia_url = self._generate_wikipedia_url(country_name)

                    # Create CountryOverview record (id will be generated by database)
                    batch_records.append(
                        CountryOverview(
                            id="",  # Will be generated by database
                            country_id=country_id,
                            body=assignment.body,
                            wikipedia_url=wikipedia_url,
                        )
                    )

                all_overview_records.extend(batch_records)
                processed_countries += len(batch_countries)

                print(
                    f"[country_overview] Batch {batch_num} completed: {len(batch_records)} overview records created"
                )

            except Exception as e:
                print(
                    f"[country_overview] Error processing batch {batch_num}: {e}"
                )
                raise

        # Insert all records into the database
        if all_overview_records:
            print(
                f"[country_overview] Inserting {len(all_overview_records)} overview records into database..."
            )
            try:
                # Use insert_many with upsert handling
                # Note: Supabase will handle ON CONFLICT automatically based on the unique constraint
                inserted = self.country_overview_repo.insert_many(all_overview_records)
                print(
                    f"[country_overview] Successfully inserted {len(inserted)} overview records"
                )
            except Exception as e:
                # If there are duplicate key conflicts, try inserting one by one
                print(
                    f"[country_overview] Bulk insert failed (possibly due to duplicates), trying individual inserts: {e}"
                )
                inserted_count = 0
                for record in all_overview_records:
                    try:
                        self.country_overview_repo.insert(record)
                        inserted_count += 1
                    except Exception as insert_error:
                        # Ignore duplicate key errors
                        if "duplicate" in str(insert_error).lower() or "unique" in str(insert_error).lower():
                            continue
                        raise
                print(
                    f"[country_overview] Successfully inserted {inserted_count} overview records (some may have been duplicates)"
                )

        print("[country_overview] Generation completed successfully!")
        print(f"[country_overview] Statistics:")
        print(f"[country_overview]   - Countries processed: {processed_countries}")
        print(f"[country_overview]   - Total overview records: {len(all_overview_records)}")

