"""LLM-based generator for country-specific AI suggestions."""

from pathlib import Path
from typing import Dict, List

from generators.llm.base_ai_suggest_generator import BaseAISuggestGenerator
from utils.database.country_ai_suggest_repository import CountryAISuggest
from utils.database.country_repository import Country, CountryRepository
from utils.ai.openai.country_ai_suggest_assignment import (
    CountrySpecificAISuggestAssignmentClient,
)
from utils.settings.voyager_settings import VoyagerSeedSettings


class CountrySpecificAISuggestGenerator(BaseAISuggestGenerator):
    """Generator for country-specific AI suggestions table using LLM."""

    def __init__(self, settings: VoyagerSeedSettings):
        """Initialize the generator.

        Args:
            settings: Voyager seed settings for configuration.
        """
        super().__init__(settings)
        self.country_repo = CountryRepository(settings)
        self.openai_client = CountrySpecificAISuggestAssignmentClient(settings)
        print(
            f"[country_specific_ai_suggests] Initialized with batch size: {CountrySpecificAISuggestAssignmentClient.BATCH_SIZE}"
        )

    def generate(self, output_path: Path) -> None:
        """Generate country-specific AI suggestions using LLM and write directly to database.

        This method:
        1. Fetches all countries from the database
        2. Processes countries in batches using OpenAI
        3. Writes results directly to the country_ai_suggests table

        Args:
            output_path: Path parameter (not used, as we write directly to DB).
        """
        print("[country_specific_ai_suggests] Starting generation...")

        # Fetch all countries
        print("[country_specific_ai_suggests] Fetching countries from database...")
        countries = self.country_repo.get_all()
        print(f"[country_specific_ai_suggests] Found {len(countries)} countries")

        if not countries:
            print("[country_specific_ai_suggests] No countries found in database, skipping generation")
            return

        # Create a mapping of country ISO2 to country ID
        country_iso2_to_id: Dict[str, str] = {
            country.iso2: country.id for country in countries
        }

        # Process countries in batches
        batch_size = CountrySpecificAISuggestAssignmentClient.BATCH_SIZE
        total_batches = (len(countries) + batch_size - 1) // batch_size
        print(
            f"[country_specific_ai_suggests] Processing {len(countries)} countries in {total_batches} batch(es) of {batch_size}"
        )

        all_suggest_records: List[CountryAISuggest] = []
        processed_countries = 0

        for batch_idx in range(0, len(countries), batch_size):
            batch_countries = countries[batch_idx : batch_idx + batch_size]
            batch_num = (batch_idx // batch_size) + 1

            print(
                f"[country_specific_ai_suggests] Processing batch {batch_num}/{total_batches} ({len(batch_countries)} countries)..."
            )

            try:
                # Call OpenAI to get suggestions for countries in this batch
                assignments = self.openai_client.get_suggests_for_countries(
                    batch_countries
                )

                # Convert assignments to CountryAISuggest records
                batch_records: List[CountryAISuggest] = []
                for assignment in assignments:
                    country_id = country_iso2_to_id.get(assignment.country_iso2)
                    if not country_id:
                        print(
                            f"[country_specific_ai_suggests] Warning: Country {assignment.country_iso2} not found in database, skipping"
                        )
                        continue

                    # Create CountryAISuggest record (id will be generated by database)
                    batch_records.append(
                        CountryAISuggest(
                            id="",  # Will be generated by database
                            country_id=country_id,
                            suggest_text=assignment.suggest_text,
                            prompt=assignment.prompt,
                        )
                    )

                all_suggest_records.extend(batch_records)
                processed_countries += len(batch_countries)

                print(
                    f"[country_specific_ai_suggests] Batch {batch_num} completed: {len(batch_records)} suggestion records created"
                )

            except Exception as e:
                print(
                    f"[country_specific_ai_suggests] Error processing batch {batch_num}: {e}"
                )
                raise

        # Insert all records into the database using base class method
        self._insert_records(all_suggest_records, "[country_specific_ai_suggests]")

        print("[country_specific_ai_suggests] Generation completed successfully!")
        print(f"[country_specific_ai_suggests] Statistics:")
        print(f"[country_specific_ai_suggests]   - Countries processed: {processed_countries}")
        print(f"[country_specific_ai_suggests]   - Total suggestion records: {len(all_suggest_records)}")

