"""LLM-based generator for general AI suggestions (not country-specific)."""

from pathlib import Path
from typing import List

from generators.llm.base_ai_suggest_generator import BaseAISuggestGenerator
from utils.database.country_ai_suggest_repository import CountryAISuggest
from utils.ai.openai.country_ai_suggest_assignment import (
    GeneralAISuggestAssignmentClient,
)
from utils.settings.voyager_settings import VoyagerSeedSettings


class GeneralAISuggestGenerator(BaseAISuggestGenerator):
    """Generator for general AI suggestions table using LLM."""

    def __init__(self, settings: VoyagerSeedSettings):
        """Initialize the generator.

        Args:
            settings: Voyager seed settings for configuration.
        """
        super().__init__(settings)
        self.openai_client = GeneralAISuggestAssignmentClient(settings)
        print(
            f"[general_ai_suggests] Initialized with OpenAI client"
        )

    def generate(self, output_path: Path) -> None:
        """Generate general AI suggestions using LLM and write directly to database.

        This method:
        1. Calls OpenAI to get general suggestions
        2. Writes results directly to the country_ai_suggests table (with country_id = NULL)

        Args:
            output_path: Path parameter (not used, as we write directly to DB).
        """
        print("[general_ai_suggests] Starting generation...")

        try:
            # Call OpenAI to get general suggestions
            print("[general_ai_suggests] Calling OpenAI to generate general suggestions...")
            assignments = self.openai_client.get_suggests()

            # Convert assignments to CountryAISuggest records (country_id = None for general)
            all_suggest_records: List[CountryAISuggest] = []
            for assignment in assignments:
                # Create CountryAISuggest record (id will be generated by database)
                all_suggest_records.append(
                    CountryAISuggest(
                        id="",  # Will be generated by database
                        country_id=None,  # General suggestions are not country-specific
                        suggest_text=assignment.suggest_text,
                        prompt=assignment.prompt,
                    )
                )

            print(
                f"[general_ai_suggests] Generated {len(all_suggest_records)} general suggestion records"
            )

        except Exception as e:
            print(
                f"[general_ai_suggests] Error generating suggestions: {e}"
            )
            raise

        # Insert all records into the database using base class method
        self._insert_records(all_suggest_records, "[general_ai_suggests]")

        print("[general_ai_suggests] Generation completed successfully!")
        print(f"[general_ai_suggests] Statistics:")
        print(f"[general_ai_suggests]   - Total suggestion records: {len(all_suggest_records)}")

